// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOcaobUwbUsTqgtpzH8WubZAddVvyJu3c',
    appId: '1:394843150811:web:e2bc5a42951d941d12affe',
    messagingSenderId: '394843150811',
    projectId: 'aarogya-bf729',
    authDomain: 'aarogya-bf729.firebaseapp.com',
    storageBucket: 'aarogya-bf729.appspot.com',
    measurementId: 'G-PLHDFZ8RRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoOLHJL_b9UGjY3IC-1C5-swFZNHWNInk',
    appId: '1:394843150811:android:3b306f7daa2ca0ab12affe',
    messagingSenderId: '394843150811',
    projectId: 'aarogya-bf729',
    storageBucket: 'aarogya-bf729.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcKDv-t--wqRaON-qcyjYIYRqDZ4Z52D0',
    appId: '1:394843150811:ios:8119ca864abe22e812affe',
    messagingSenderId: '394843150811',
    projectId: 'aarogya-bf729',
    storageBucket: 'aarogya-bf729.appspot.com',
    iosBundleId: 'com.example.aarogya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcKDv-t--wqRaON-qcyjYIYRqDZ4Z52D0',
    appId: '1:394843150811:ios:8119ca864abe22e812affe',
    messagingSenderId: '394843150811',
    projectId: 'aarogya-bf729',
    storageBucket: 'aarogya-bf729.appspot.com',
    iosBundleId: 'com.example.aarogya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOcaobUwbUsTqgtpzH8WubZAddVvyJu3c',
    appId: '1:394843150811:web:756482b87d36f54e12affe',
    messagingSenderId: '394843150811',
    projectId: 'aarogya-bf729',
    authDomain: 'aarogya-bf729.firebaseapp.com',
    storageBucket: 'aarogya-bf729.appspot.com',
    measurementId: 'G-MB8ZEW1LXX',
  );
}
